### ISSUE TITLE
C++ Code for Fun

### ISSUE THREAD

**Issue by VonHirsch** [0xFA11/MultiplayerNetworkingResources#1]
Just a suggestion but why not include some code on your repo?  Just for browsing.  Like maybe some source code from Quake3

Thanks for the great repo!

**Comment by 0xFA11** [comment]
Hey,

Thank you for suggestion but unfortunately I disagree about having code in this repo even if they are small.
The main purpose of this repo is to provide a curated list of game network programming resources as stated in description.

It's hard to maintain both code and valuable resources at the same time.
Also I believe that people don't want to bother with source code here.

However, we already have 2 articles listed about Quake networking model.
Beyond that, I'm trying to find some free time and update the list with more projects, tutorials, talks and articles.

Lastly, please consider contributing good network programming stuff if you have anything in your mind, I will highly appreciate them :)

Thanks,
Fatih

**Comment by VonHirsch** [comment]
Sounds good thanks!
