### ISSUE TITLE
Academics? Awesome?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [0xFA11/MultiplayerNetworkingResources#16]
I have found one academic papers (seems good) about games networking. Not sure if it is awesome? 

https://brage.bibsys.no/xmlui/bitstream/handle/11250/2352307/11752_FULLTEXT.pdf

May be there are other academic resources?

**Comment by 0xFA11** [comment]
The paper is absolutely "awesome" 😎 
I believe there are tons of other awesome (and not-so-awesome) academic paper out there.
We should also keep eye on them and cherry-pick the good ones.

I will add this paper to articles section with a proper description when I get a chance.
Thank you! 🎉

**Comment by 0xFA11** [comment]
Added to Articles section with commit 6686fec

Thanks again!
