### ISSUE TITLE
gafferongames.com dead?

### ISSUE THREAD

**Issue by sleepyspider1** [0xFA11/MultiplayerNetworkingResources#23]
Is it dead?

**Comment by ascherbakhov** [comment]
Yes, I can't get access to it for about half of year. But you can get access to it through archive.org
[http://web.archive.org/web/20190328001900/https://gafferongames.com/](http://web.archive.org/web/20190328001900/https://gafferongames.com/)

**Comment by 0xFA11** [comment]
Unfortunately, site seems broken — as a temporary fix, I'll update the link with archive.org
Thank you guys!
