### ISSUE TITLE
darkRift c#

### ISSUE THREAD

**Issue by geeksesi** [0xFA11/MultiplayerNetworkingResources#25]
Hi,
darkrift[1,2] are good framework for multiplayer

https://darkriftnetworking.com/

also a tutorial : 
[materiagame](https://materiagame.com/complete-darkrift2-tutorials-for-unity3d-network-games)

**Comment by 0xFA11** [comment]
Hey @geeksesi,

Thanks for your contribution, they look good!
I will include them — thank you! :)
