### ISSUE TITLE
"The Server Technology of EVE Online" talk seems to be not available anymore

### ISSUE THREAD

**Issue by ondrowan** [0xFA11/MultiplayerNetworkingResources#29]
I'm not sure if it's just region restriction, but it says for me "This content is not available"

https://www.gdcvault.com/play/1014031/The-Server-Technology-of-EVE

**Comment by 0xFA11** [comment]
Hello, thanks for the issue — sorry for my late response.

I double-checked with and without my GDC Vault account, it looks like it's not private or members only, it's taken down entirely!
Unfortunately, I will remove the entry from the list :(
