### ISSUE TITLE
"Ethernet vs WiFi" link is down

### ISSUE THREAD

**Issue by coolantleak** [0xFA11/MultiplayerNetworkingResources#39]
The link seems to be redirecting to a LoL news home page. I found a cached version [here](https://web.archive.org/web/20191231135556/http://na.leagueoflegends.com/en/page/ethernet-vs-wifi-ping-packets-playing-better)

**Comment by 0xFA11** [comment]
Hey @mxsilva ,

Thank you for reporting this issue!

I will be updating the list and using a webarchive link as a fallback when I get a chance.

**Comment by 0xFA11** [comment]
Hello again,

I have updated the link with Archive.org backup (see commit bedb2d9).

Thank you for reporting that issue after you noticed — cheers!
