### ISSUE TITLE
Request to Add Unity GONet

### ISSUE THREAD

**Issue by shasheppard** [0xFA11/MultiplayerNetworkingResources#43]
I am the author of Unity GONet (see https://assetstore.unity.com/packages/tools/network/gonet-154576 and https://unitygo.net).  The Unity asset comes with ALL SOURCE and the asset is FREE.

I would like for GONet to be reviewed and considered for addition to the list on this site.  If there is a more appropriate way to make this request, I will gladly do that.  Thank you.

**Comment by 0xFA11** [comment]
Hey @shasheppard,
I'm really sorry to reply this late :(
Do you mind explaining what this project is about and also summarize it in one line?
And, thank you for this issue!

**Comment by shasheppard** [comment]
No problem.

Here is a one liner for the C# section:

   - <a href="https://unitygo.net">GONet</a> - GameObject-centric
   multiplayer networking for Unity that is dead simple to get started yet
   offers a rich depth of capability.

And here is a bit more:
GONet is the Unity3D GameObject Networking solution with tight,
developer-friendly integration into the Unity architecture/runtime. If you
need to network something and a GameObject is involved, GONet is the
answer.  GONet offers auto-magical data sync & value blending & compression
& encryption, extensible pub/sub events, High+Low level API, pure C# w/ all
source code.

I am glad to go into more depth.  If you want a better flavor for it, check
out our youtube page: GONet - YouTube
<https://www.youtube.com/channel/UClkvaQmqFgu2DdXBj9c1fMA>

Thank you for your time.


--Shaun

**Comment by 0xFA11** [comment]
Looks like this project is no longer active :/
Website is gone, also package is no longer available on AssetStore.
